AllCops:
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "config/**/*"
    - "node_modules/**/*"
    - "script/**/*"
    - "support/**/*"
    - "tmp/**/*"
  NewCops: enable

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
