AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/seeds.rb
    - config/**/*
    - node_modules/**/*
    - script/**/*
    - support/**/*
    - tmp/**/*
    - vendor/bundle/**/*
  NewCops: enable

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
